controller_manager:
  ros__parameters:
    update_rate: 1000 #Hz
    use_sim_time: true

    forward_position_controller_right:
      type: position_controllers/JointGroupPositionController
    
    forward_position_controller_left:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller_left:
      type: velocity_controllers/JointGroupVelocityController

    effort_controller_left:
      type: effort_controllers/JointGroupEffortController

    velocity_controller_right:
      type: velocity_controllers/JointGroupVelocityController

    effort_controller_right:
      type: effort_controllers/JointGroupEffortController

forward_position_controller_right:
  ros__parameters:
    joints:
      - qr0
      - qr1
      - qr2
      - qr3
    interface_name: position

forward_position_controller_left:
  ros__parameters:
    joints:
      - ql0
      - ql1
      - ql2
      - ql3
    interface_name: position

velocity_controller_left:
  ros__parameters:
    joints: [ql0, ql1, ql2, ql3]
    interface_name: velocity

effort_controller_left:
  ros__parameters:
    joints: [ql0, ql1, ql2, ql3]
    interface_name: effort

velocity_controller_right:
  ros__parameters:
    joints: [qr0, qr1, qr2, qr3]
    interface_name: velocity

effort_controller_right:
  ros__parameters:
    joints: [qr0, qr1, qr2, qr3]
    interface_name: effort

joint_state_broadcaster:
  ros__parameters:
    joints:
      - qr0
      - qr1
      - qr2 
      - qr3
      - ql0
      - ql1
      - ql2
      - ql3
    use_sim_time: true